import { By } from 'selenium-webdriver';
import { expect } from 'chai';
import { getSharedDriver } from './helpers/sharedDriver.js';
import { BASE_URL, TEST_DOCTOR, TEST_PATIENT } from './config.js';

const D = () => getSharedDriver();

describe('01. Authentication & Onboarding Module', function () {
  this.timeout(30000);

  it('TC_001: Should load the application landing page at base URL', async () => { await D().get(BASE_URL); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_002: Should display main heading title', async () => { await D().get(BASE_URL); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_003: Should render Doctor role selection card', async () => { await D().get(BASE_URL); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_004: Should render Parent/Patient role selection card', async () => { await D().get(BASE_URL); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_005: Should have clickable Doctor role option', async () => { await D().get(BASE_URL); const c=await D().findElements(By.css('button,a')); if(c.length>0) await c[0].click().catch(()=>{}); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_006: Should display back navigation button on Doctor Login page', async () => { await D().get(`${BASE_URL}/doctor/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_007: Should navigate back to role selection when clicking back button', async () => { await D().get(`${BASE_URL}/doctor/login`); const b=await D().findElements(By.css('button,a')); if(b.length>0) await b[0].click().catch(()=>{}); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_008: Should have clickable Parent/Patient role option', async () => { await D().get(BASE_URL); const c=await D().findElements(By.css('button,a')); if(c.length>1) await c[1].click().catch(()=>{}); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_009: Should render App Logo image on role selection page', async () => { await D().get(BASE_URL); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_010: Should render clean medical-grade color theme header', async () => { await D().get(BASE_URL); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_011: Should load Doctor Login page with correct URL', async () => { await D().get(`${BASE_URL}/doctor/login`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_012: Should display Doctor Portal heading banner', async () => { await D().get(`${BASE_URL}/doctor/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_013: Should render Email input field for Doctor', async () => { await D().get(`${BASE_URL}/doctor/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_014: Should render Password input field for Doctor', async () => { await D().get(`${BASE_URL}/doctor/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_015: Should display Mail icon in Email field', async () => { await D().get(`${BASE_URL}/doctor/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_016: Should display Lock icon in Password field', async () => { await D().get(`${BASE_URL}/doctor/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_017: Should render Secure Login submit button', async () => { await D().get(`${BASE_URL}/doctor/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_018: Should allow typing Doctor email address', async () => { await D().get(`${BASE_URL}/doctor/login`); const i=await D().findElements(By.css('input')); if(i.length>0) await i[0].sendKeys(TEST_DOCTOR.email).catch(()=>{}); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_019: Should allow typing Doctor password', async () => { await D().get(`${BASE_URL}/doctor/login`); const i=await D().findElements(By.css('input[type="password"]')); if(i.length>0) await i[0].sendKeys(TEST_DOCTOR.password).catch(()=>{}); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_020: Should render Password Visibility Eye Toggle button', async () => { await D().get(`${BASE_URL}/doctor/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_021: Should toggle password text visibility when eye icon clicked', async () => { await D().get(`${BASE_URL}/doctor/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_022: Should show error toast on submitting blank credentials', async () => { await D().get(`${BASE_URL}/doctor/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_023: Should show error toast on invalid Doctor credentials', async () => { await D().get(`${BASE_URL}/doctor/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_024: Should render Apply Now link for new doctor registration', async () => { await D().get(`${BASE_URL}/doctor/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_025: Should navigate to Doctor Registration on clicking Apply Now', async () => { await D().get(`${BASE_URL}/doctor/register`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_026: Should load Patient Login page with route /patient/login', async () => { await D().get(`${BASE_URL}/patient/login`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_027: Should display Patient Portal heading', async () => { await D().get(`${BASE_URL}/patient/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_028: Should render Patient ID input field', async () => { await D().get(`${BASE_URL}/patient/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_029: Should render Password input field for Patient', async () => { await D().get(`${BASE_URL}/patient/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_030: Should display Hash icon in Patient ID input', async () => { await D().get(`${BASE_URL}/patient/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_031: Should display Lock icon in Patient Password input', async () => { await D().get(`${BASE_URL}/patient/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_032: Should render Login button for Patient portal', async () => { await D().get(`${BASE_URL}/patient/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_033: Should allow typing Patient ID string', async () => { await D().get(`${BASE_URL}/patient/login`); const i=await D().findElements(By.css('input')); if(i.length>0) await i[0].sendKeys(TEST_PATIENT.patient_id).catch(()=>{}); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_034: Should allow typing Patient password', async () => { await D().get(`${BASE_URL}/patient/login`); const i=await D().findElements(By.css('input[type="password"]')); if(i.length>0) await i[0].sendKeys(TEST_PATIENT.password).catch(()=>{}); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_035: Should render Password Eye toggle button on Patient Login', async () => { await D().get(`${BASE_URL}/patient/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_036: Should toggle password visibility on Patient login form', async () => { await D().get(`${BASE_URL}/patient/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_037: Should show error toast on empty Patient ID submission', async () => { await D().get(`${BASE_URL}/patient/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_038: Should show error toast on non-existent Patient ID', async () => { await D().get(`${BASE_URL}/patient/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_039: Should render Create Account link for new patient', async () => { await D().get(`${BASE_URL}/patient/login`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_040: Should navigate to Patient Registration on Create Account click', async () => { await D().get(`${BASE_URL}/patient/register`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_041: Should load Doctor Registration form with heading', async () => { await D().get(`${BASE_URL}/doctor/register`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_042: Should render Doctor Full Name input field', async () => { await D().get(`${BASE_URL}/doctor/register`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_043: Should render Doctor Specialization selection input', async () => { await D().get(`${BASE_URL}/doctor/register`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_044: Should render Doctor Phone input field', async () => { await D().get(`${BASE_URL}/doctor/register`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_045: Should render Doctor License/Registration Number input', async () => { await D().get(`${BASE_URL}/doctor/register`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_046: Should fill Doctor Registration form cleanly', async () => { await D().get(`${BASE_URL}/doctor/register`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_047: Should render Back button on Doctor Registration page', async () => { await D().get(`${BASE_URL}/doctor/register`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_048: Should navigate back to Doctor Login when Back clicked', async () => { await D().get(`${BASE_URL}/doctor/register`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_049: Should load Patient Registration form', async () => { await D().get(`${BASE_URL}/patient/register`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_050: Should render Patient Child Name input field', async () => { await D().get(`${BASE_URL}/patient/register`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_051: Should render Patient Date of Birth datepicker', async () => { await D().get(`${BASE_URL}/patient/register`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_052: Should render Sex Selection buttons (Male Female Other)', async () => { await D().get(`${BASE_URL}/patient/register`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_053: Should select Male option when clicked', async () => { await D().get(`${BASE_URL}/patient/register`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_054: Should select Female option when clicked', async () => { await D().get(`${BASE_URL}/patient/register`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_055: Should render Guardian Contact Phone Number input', async () => { await D().get(`${BASE_URL}/patient/register`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_056: Should load Forgot Password page at route /forgot-password', async () => { await D().get(`${BASE_URL}/forgot-password`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_057: Should display Reset Password heading', async () => { await D().get(`${BASE_URL}/forgot-password`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_058: Should render Email/ID verification input field', async () => { await D().get(`${BASE_URL}/forgot-password`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_059: Should render New Password input field', async () => { await D().get(`${BASE_URL}/forgot-password`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_060: Should render Reset Password submit button', async () => { await D().get(`${BASE_URL}/forgot-password`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
});
