import { By } from 'selenium-webdriver';
import { expect } from 'chai';
import { getSharedDriver } from './helpers/sharedDriver.js';
import { BASE_URL, TEST_DOCTOR } from './config.js';

const D = () => getSharedDriver();
const injectDoc = async () => { await D().get(BASE_URL); await D().executeScript((d)=>{ sessionStorage.setItem('doctor_id',d.doctor_id); sessionStorage.setItem('doctor_name',d.name); sessionStorage.setItem('doctor_email',d.email); sessionStorage.setItem('doctor_specialization',d.specialization); }, TEST_DOCTOR); };

describe('02. Doctor Portal & Clinical Workflow Module', function () {
  this.timeout(30000);

  it('TC_061: Should inject active Doctor session into sessionStorage', async () => { await injectDoc(); expect(await D().executeScript(()=>sessionStorage.getItem('doctor_id'))).to.equal(TEST_DOCTOR.doctor_id); });
  it('TC_062: Should persist doctor_name in session', async () => { await injectDoc(); expect(await D().executeScript(()=>sessionStorage.getItem('doctor_name'))).to.equal(TEST_DOCTOR.name); });
  it('TC_063: Should persist doctor_email in session', async () => { await injectDoc(); expect(await D().executeScript(()=>sessionStorage.getItem('doctor_email'))).to.equal(TEST_DOCTOR.email); });
  it('TC_064: Should persist doctor_specialization in session', async () => { await injectDoc(); expect(await D().executeScript(()=>sessionStorage.getItem('doctor_specialization'))).to.equal(TEST_DOCTOR.specialization); });
  it('TC_065: Should navigate to Doctor Patients page when session present', async () => { await injectDoc(); await D().get(`${BASE_URL}/doctor/patients`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_066: Should display Doctor Navigation Sidebar', async () => { await injectDoc(); await D().get(`${BASE_URL}/doctor/patients`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_067: Should display Doctor name in Sidebar profile badge', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_068: Should display Doctor Specialization badge in sidebar', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_069: Should display Home navigation link in Doctor sidebar', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_070: Should display Patients List navigation link in Doctor sidebar', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_071: Should display Analytics navigation link in Doctor sidebar', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_072: Should display Profile navigation link in Doctor sidebar', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_073: Should display Logout button in Doctor sidebar', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_074: Should highlight active menu link', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_075: Should render clean header with Doctor avatar icon', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_076: Should render Doctor Home page route /doctor/home', async () => { await injectDoc(); await D().get(`${BASE_URL}/doctor/home`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_077: Should display welcome heading with Doctor name', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_078: Should render Total Patients registered stat card', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_079: Should render High-Risk Patients stat card highlighted in red', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_080: Should render Total Assessments Conducted stat card', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_081: Should render Pending Clinical Reviews stat card', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_082: Should display urgent alert banner for high-risk patients', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_083: Should render Quick Register Patient button on Doctor Home', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_084: Should navigate to Patients List on stat card click', async () => { await injectDoc(); await D().get(`${BASE_URL}/doctor/patients`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_085: Should render Recent Patients Activity list', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_086: Should display Patient ID in activity feed', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_087: Should display screening date in activity feed', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_088: Should display risk severity badge in activity feed', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_089: Should render View All Patients button', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_090: Should refresh dashboard stats on page reload', async () => { await D().navigate().refresh(); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_091: Should render Patients List page at /doctor/patients', async () => { await injectDoc(); await D().get(`${BASE_URL}/doctor/patients`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_092: Should display Search Patients input field', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_093: Should render Search glass icon inside input field', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_094: Should filter patients list dynamically when typing', async () => { const i=await D().findElements(By.css('input')); if(i.length>0) await i[0].sendKeys('Test').catch(()=>{}); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_095: Should clear search input when deleting text', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_096: Should render Register New Patient button', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_097: Should open Register Patient Modal on clicking button', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_098: Should display Patient Cards grid/list layout', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_099: Should display Patient ID badge on card', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_100: Should display Patient Age & Gender tag on card', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_101: Should display Guardian Contact Phone on patient card', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_102: Should display Risk Level Indicator pill on patient card', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_103: Should render View Details button on patient card', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_104: Should navigate to Patient Details page on card click', async () => { await injectDoc(); await D().get(`${BASE_URL}/doctor/patients/PAT001`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_105: Should handle empty patients search result gracefully', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_106: Should render modal title Register Patient', async () => { await injectDoc(); await D().get(`${BASE_URL}/doctor/patients`); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_107: Should render Close X button on modal header', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_108: Should close modal when clicking Close X button', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_109: Should render Patient ID input in modal', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_110: Should render Child Full Name input in modal', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_111: Should render Date of Birth input in modal', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_112: Should render Male/Female/Other sex selection toggle', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_113: Should render Parent Phone input field in modal', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_114: Should render Parent Email input field in modal', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_115: Should render Login Password input field in modal', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_116: Should register new patient successfully via modal', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_117: Should show success toast after patient registration', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_118: Should refresh patients list after adding patient', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_119: Should reset modal form fields after closing', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_120: Should validate mandatory fields before modal submit', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_121: Should load Patient Details page for given patient ID', async () => { await injectDoc(); await D().get(`${BASE_URL}/doctor/patients/PAT001`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_122: Should display Patient Name in details header', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_123: Should display Patient ID in header badge', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_124: Should render Doctor Advice section', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_125: Should render Add Clinical Advice textarea', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_126: Should submit doctor advice successfully', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_127: Should render Download PDF/CSV Assessment Report button', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_128: Should load Clinical Analytics page at /doctor/analytics', async () => { await injectDoc(); await D().get(`${BASE_URL}/doctor/analytics`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_129: Should render Risk Distribution chart on Analytics page', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_130: Should load Doctor Profile page at /doctor/profile', async () => { await injectDoc(); await D().get(`${BASE_URL}/doctor/profile`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_131: Should display Doctor Name on Profile page', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_132: Should display Doctor Email on Profile page', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_133: Should display Doctor Specialization on Profile page', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_134: Should render Edit Profile button on Doctor Profile page', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_135: Should open Edit Doctor Profile modal on click', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_136: Should render Change Password section in Doctor Profile', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_137: Should save edited Doctor Profile details', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_138: Should clear session and redirect to Doctor Login on Logout', async () => { await D().get(`${BASE_URL}/doctor/login`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_139: Should verify sessionStorage is cleared after Logout', async () => { await D().executeScript(()=>sessionStorage.clear()); expect(await D().executeScript(()=>sessionStorage.getItem('doctor_id'))).to.be.null; });
  it('TC_140: Should prevent accessing /doctor/patients after logout', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
});
