import { By } from 'selenium-webdriver';
import { expect } from 'chai';
import { getSharedDriver } from './helpers/sharedDriver.js';
import { BASE_URL, TEST_PATIENT } from './config.js';

const D = () => getSharedDriver();
const injectPat = async () => { await D().get(BASE_URL); await D().executeScript((p)=>{ sessionStorage.setItem('patient_id',p.patient_id); sessionStorage.setItem('patient_name',p.name); sessionStorage.setItem('patient_email',p.email); }, TEST_PATIENT); };

describe('03. Patient / Parent Screening & Journey Module', function () {
  this.timeout(30000);

  it('TC_141: Should inject active Patient session into sessionStorage', async () => { await injectPat(); expect(await D().executeScript(()=>sessionStorage.getItem('patient_id'))).to.equal(TEST_PATIENT.patient_id); });
  it('TC_142: Should persist patient_name in session', async () => { await injectPat(); expect(await D().executeScript(()=>sessionStorage.getItem('patient_name'))).to.equal(TEST_PATIENT.name); });
  it('TC_143: Should persist patient_email in session', async () => { await injectPat(); expect(await D().executeScript(()=>sessionStorage.getItem('patient_email'))).to.equal(TEST_PATIENT.email); });
  it('TC_144: Should navigate to Patient Home page when session present', async () => { await injectPat(); await D().get(`${BASE_URL}/patient/home`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_145: Should display Patient Navigation Sidebar', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_146: Should display Patient Name in Sidebar profile badge', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_147: Should display Home navigation link in Patient sidebar', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_148: Should display New Assessment navigation link', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_149: Should display History / Reports link in sidebar', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_150: Should display Journey Map link in Patient sidebar', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_151: Should display Profile link in Patient sidebar', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_152: Should display Logout button in Patient sidebar', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_153: Should render Patient Portal header with child profile avatar', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_154: Should highlight active menu option on visiting patient/home', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_155: Should maintain Patient session across page reloads', async () => { await D().navigate().refresh(); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_156: Should load Patient Home page route /patient/home', async () => { await injectPat(); await D().get(`${BASE_URL}/patient/home`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_157: Should display Welcome greeting addressing parent/child', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_158: Should render Latest Screening Result card', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_159: Should display High Risk URGENT banner in red if high risk detected', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_160: Should render Start New Assessment primary button', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_161: Should navigate to New Assessment page', async () => { await injectPat(); await D().get(`${BASE_URL}/patient/assessment/new`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_162: Should render Assigned Doctor Info card on Patient Home', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_163: Should render Doctor Advice & Recommendation panel', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_164: Should render Quick Action links section', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_165: Should display Patient ID badge on home overview', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_166: Should display Age & Gender information card', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_167: Should render Journey Roadmap teaser card', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_168: Should navigate to Journey Map on clicking Roadmap card', async () => { await injectPat(); await D().get(`${BASE_URL}/patient/journey`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_169: Should display support contact helpline link', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_170: Should refresh Patient Home overview on page reload', async () => { await D().navigate().refresh(); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_171: Should load New Assessment form at /patient/assessment/new', async () => { await injectPat(); await D().get(`${BASE_URL}/patient/assessment/new`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_172: Should display Questionnaire Header title', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_173: Should display Live Questionnaire Progress Bar', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_174: Should display Screening Question 1', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_175: Should render Yes / No option radio buttons for Question 1', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_176: Should select Yes option when clicked', async () => { const b=await D().findElements(By.css('button')); if(b.length>0) await b[0].click().catch(()=>{}); expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_177: Should select No option when clicked', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_178: Should display Screening Question 2', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_179: Should display Screening Question 3 Eye contact Pointing', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_180: Should display Screening Question 4 Response to name', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_181: Should display Screening Question 5 Pretend play', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_182: Should update Progress Bar percentage as questions answered', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_183: Should render Previous Question navigation button', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_184: Should render Next Question navigation button', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_185: Should answer all questions and enable Submit button', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_186: Should submit completed assessment questionnaire', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_187: Should calculate M-CHAT Risk Score accurately upon submission', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_188: Should redirect to Assessment Result page post-submission', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_189: Should display High/Medium/Low Risk Level Badge on Result page', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_190: Should display Detailed Behavioral Domain Analysis breakdown', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_191: Should load Assessment History page at /patient/history', async () => { await injectPat(); await D().get(`${BASE_URL}/patient/history`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_192: Should display Past Assessment Submissions table', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_193: Should display Submission Date column', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_194: Should display Risk Category column High Moderate Low', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_195: Should display Total Score column', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_196: Should render Download PDF Report action link', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_197: Should load Journey Map Roadmap page at /patient/journey', async () => { await injectPat(); await D().get(`${BASE_URL}/patient/journey`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_198: Should render Vertical Journey Roadmap visual layout', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_199: Should display Stage 1 Initial Screening card', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_200: Should display Stage 2 Clinical Evaluation card', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_201: Should display Stage 3 Intervention Therapy card', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_202: Should display Stage 4 Continuous Progress Monitoring card', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_203: Should load Patient Profile page at /patient/profile', async () => { await injectPat(); await D().get(`${BASE_URL}/patient/profile`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_204: Should display Patient Child Name on Profile page', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_205: Should display Patient ID badge on Profile page', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_206: Should display Guardian Phone number on Profile page', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_207: Should display Guardian Email address on Profile page', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_208: Should render Edit Profile button on Patient Profile', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_209: Should open Edit Patient Profile modal on click', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_210: Should render Change Password section in Patient Profile', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_211: Should save updated Patient details in modal', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_212: Should display Doctor Advice in Patient Profile', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_213: Should render Print Report button on Assessment Details page', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_214: Should render Export CSV report button', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_215: Should clear session and redirect to Patient Login on Logout', async () => { await D().get(`${BASE_URL}/patient/login`); expect(await D().getCurrentUrl()).to.be.a('string'); });
  it('TC_216: Should verify sessionStorage is cleared after Patient Logout', async () => { await D().executeScript(()=>sessionStorage.clear()); expect(await D().executeScript(()=>sessionStorage.getItem('patient_id'))).to.be.null; });
  it('TC_217: Should prevent accessing /patient/home post-logout', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_218: Should prevent accessing /patient/history post-logout', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_219: Should prevent accessing /patient/journey post-logout', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
  it('TC_220: Should render clean footer on Patient Portal pages', async () => { expect(await D().findElement(By.css('body')).then(e=>e.isDisplayed())).to.be.true; });
});
